// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trace.proto

package ai;

public final class Trace {
  private Trace() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TraceArgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ai.TraceArg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes trace_id = 1;</code>
     */
    com.google.protobuf.ByteString getTraceId();

    /**
     * <code>bool debug = 2;</code>
     */
    boolean getDebug();

    /**
     * <code>bytes task_id = 3;</code>
     */
    com.google.protobuf.ByteString getTaskId();

    /**
     * <code>bool is_baseline = 4;</code>
     */
    boolean getIsBaseline();
  }
  /**
   * Protobuf type {@code ai.TraceArg}
   */
  public  static final class TraceArg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ai.TraceArg)
      TraceArgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TraceArg.newBuilder() to construct.
    private TraceArg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TraceArg() {
      traceId_ = com.google.protobuf.ByteString.EMPTY;
      debug_ = false;
      taskId_ = com.google.protobuf.ByteString.EMPTY;
      isBaseline_ = false;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TraceArg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              traceId_ = input.readBytes();
              break;
            }
            case 16: {

              debug_ = input.readBool();
              break;
            }
            case 26: {

              taskId_ = input.readBytes();
              break;
            }
            case 32: {

              isBaseline_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Trace.internal_static_ai_TraceArg_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Trace.internal_static_ai_TraceArg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TraceArg.class, Builder.class);
    }

    public static final int TRACE_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString traceId_;
    /**
     * <code>bytes trace_id = 1;</code>
     */
    public com.google.protobuf.ByteString getTraceId() {
      return traceId_;
    }

    public static final int DEBUG_FIELD_NUMBER = 2;
    private boolean debug_;
    /**
     * <code>bool debug = 2;</code>
     */
    public boolean getDebug() {
      return debug_;
    }

    public static final int TASK_ID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString taskId_;
    /**
     * <code>bytes task_id = 3;</code>
     */
    public com.google.protobuf.ByteString getTaskId() {
      return taskId_;
    }

    public static final int IS_BASELINE_FIELD_NUMBER = 4;
    private boolean isBaseline_;
    /**
     * <code>bool is_baseline = 4;</code>
     */
    public boolean getIsBaseline() {
      return isBaseline_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!traceId_.isEmpty()) {
        output.writeBytes(1, traceId_);
      }
      if (debug_ != false) {
        output.writeBool(2, debug_);
      }
      if (!taskId_.isEmpty()) {
        output.writeBytes(3, taskId_);
      }
      if (isBaseline_ != false) {
        output.writeBool(4, isBaseline_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!traceId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, traceId_);
      }
      if (debug_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, debug_);
      }
      if (!taskId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, taskId_);
      }
      if (isBaseline_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isBaseline_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TraceArg)) {
        return super.equals(obj);
      }
      TraceArg other = (TraceArg) obj;

      boolean result = true;
      result = result && getTraceId()
          .equals(other.getTraceId());
      result = result && (getDebug()
          == other.getDebug());
      result = result && getTaskId()
          .equals(other.getTaskId());
      result = result && (getIsBaseline()
          == other.getIsBaseline());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TRACE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTraceId().hashCode();
      hash = (37 * hash) + DEBUG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDebug());
      hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskId().hashCode();
      hash = (37 * hash) + IS_BASELINE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsBaseline());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TraceArg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TraceArg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TraceArg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TraceArg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TraceArg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TraceArg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TraceArg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TraceArg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TraceArg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TraceArg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TraceArg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TraceArg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TraceArg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ai.TraceArg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ai.TraceArg)
        TraceArgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Trace.internal_static_ai_TraceArg_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Trace.internal_static_ai_TraceArg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TraceArg.class, Builder.class);
      }

      // Construct using ai.Trace.TraceArg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        traceId_ = com.google.protobuf.ByteString.EMPTY;

        debug_ = false;

        taskId_ = com.google.protobuf.ByteString.EMPTY;

        isBaseline_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Trace.internal_static_ai_TraceArg_descriptor;
      }

      public TraceArg getDefaultInstanceForType() {
        return TraceArg.getDefaultInstance();
      }

      public TraceArg build() {
        TraceArg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TraceArg buildPartial() {
        TraceArg result = new TraceArg(this);
        result.traceId_ = traceId_;
        result.debug_ = debug_;
        result.taskId_ = taskId_;
        result.isBaseline_ = isBaseline_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TraceArg) {
          return mergeFrom((TraceArg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TraceArg other) {
        if (other == TraceArg.getDefaultInstance()) return this;
        if (other.getTraceId() != com.google.protobuf.ByteString.EMPTY) {
          setTraceId(other.getTraceId());
        }
        if (other.getDebug() != false) {
          setDebug(other.getDebug());
        }
        if (other.getTaskId() != com.google.protobuf.ByteString.EMPTY) {
          setTaskId(other.getTaskId());
        }
        if (other.getIsBaseline() != false) {
          setIsBaseline(other.getIsBaseline());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TraceArg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TraceArg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString traceId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes trace_id = 1;</code>
       */
      public com.google.protobuf.ByteString getTraceId() {
        return traceId_;
      }
      /**
       * <code>bytes trace_id = 1;</code>
       */
      public Builder setTraceId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        traceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes trace_id = 1;</code>
       */
      public Builder clearTraceId() {
        
        traceId_ = getDefaultInstance().getTraceId();
        onChanged();
        return this;
      }

      private boolean debug_ ;
      /**
       * <code>bool debug = 2;</code>
       */
      public boolean getDebug() {
        return debug_;
      }
      /**
       * <code>bool debug = 2;</code>
       */
      public Builder setDebug(boolean value) {
        
        debug_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool debug = 2;</code>
       */
      public Builder clearDebug() {
        
        debug_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString taskId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes task_id = 3;</code>
       */
      public com.google.protobuf.ByteString getTaskId() {
        return taskId_;
      }
      /**
       * <code>bytes task_id = 3;</code>
       */
      public Builder setTaskId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes task_id = 3;</code>
       */
      public Builder clearTaskId() {
        
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }

      private boolean isBaseline_ ;
      /**
       * <code>bool is_baseline = 4;</code>
       */
      public boolean getIsBaseline() {
        return isBaseline_;
      }
      /**
       * <code>bool is_baseline = 4;</code>
       */
      public Builder setIsBaseline(boolean value) {
        
        isBaseline_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_baseline = 4;</code>
       */
      public Builder clearIsBaseline() {
        
        isBaseline_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ai.TraceArg)
    }

    // @@protoc_insertion_point(class_scope:ai.TraceArg)
    private static final TraceArg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TraceArg();
    }

    public static TraceArg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TraceArg>
        PARSER = new com.google.protobuf.AbstractParser<TraceArg>() {
      public TraceArg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TraceArg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TraceArg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TraceArg> getParserForType() {
      return PARSER;
    }

    public TraceArg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_TraceArg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ai_TraceArg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013trace.proto\022\002ai\"Q\n\010TraceArg\022\020\n\010trace_i" +
      "d\030\001 \001(\014\022\r\n\005debug\030\002 \001(\010\022\017\n\007task_id\030\003 \001(\014\022" +
      "\023\n\013is_baseline\030\004 \001(\010b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ai_TraceArg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ai_TraceArg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ai_TraceArg_descriptor,
        new String[] { "TraceId", "Debug", "TaskId", "IsBaseline", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
