// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kfc_message.proto

package ai.kfc;

public final class KfcMessage {
  private KfcMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KFCRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ai.kfc.KFCRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ai.TraceArg trace = 1;</code>
     */
    boolean hasTrace();
    /**
     * <code>.ai.TraceArg trace = 1;</code>
     */
    ai.Trace.TraceArg getTrace();
    /**
     * <code>.ai.TraceArg trace = 1;</code>
     */
    ai.Trace.TraceArgOrBuilder getTraceOrBuilder();

    /**
     * <code>string key = 3;</code>
     */
    String getKey();
    /**
     * <code>string key = 3;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>repeated string keys = 2;</code>
     */
    java.util.List<String>
        getKeysList();
    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>repeated string keys = 2;</code>
     */
    int getKeysCount();
    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>repeated string keys = 2;</code>
     */
    String getKeys(int index);
    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>repeated string keys = 2;</code>
     */
    com.google.protobuf.ByteString
        getKeysBytes(int index);
  }
  /**
   * <pre>
   * use db:key
   * example: mid_blacklist:3479095
   * </pre>
   *
   * Protobuf type {@code ai.kfc.KFCRequest}
   */
  public  static final class KFCRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ai.kfc.KFCRequest)
      KFCRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KFCRequest.newBuilder() to construct.
    private KFCRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KFCRequest() {
      key_ = "";
      keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KFCRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ai.Trace.TraceArg.Builder subBuilder = null;
              if (trace_ != null) {
                subBuilder = trace_.toBuilder();
              }
              trace_ = input.readMessage(ai.Trace.TraceArg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(trace_);
                trace_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                keys_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              keys_.add(s);
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          keys_ = keys_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return KfcMessage.internal_static_ai_kfc_KFCRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return KfcMessage.internal_static_ai_kfc_KFCRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              KFCRequest.class, Builder.class);
    }

    private int bitField0_;
    public static final int TRACE_FIELD_NUMBER = 1;
    private ai.Trace.TraceArg trace_;
    /**
     * <code>.ai.TraceArg trace = 1;</code>
     */
    public boolean hasTrace() {
      return trace_ != null;
    }
    /**
     * <code>.ai.TraceArg trace = 1;</code>
     */
    public ai.Trace.TraceArg getTrace() {
      return trace_ == null ? ai.Trace.TraceArg.getDefaultInstance() : trace_;
    }
    /**
     * <code>.ai.TraceArg trace = 1;</code>
     */
    public ai.Trace.TraceArgOrBuilder getTraceOrBuilder() {
      return getTrace();
    }

    public static final int KEY_FIELD_NUMBER = 3;
    private volatile Object key_;
    /**
     * <code>string key = 3;</code>
     */
    public String getKey() {
      Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 3;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEYS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList keys_;
    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>repeated string keys = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getKeysList() {
      return keys_;
    }
    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>repeated string keys = 2;</code>
     */
    public int getKeysCount() {
      return keys_.size();
    }
    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>repeated string keys = 2;</code>
     */
    public String getKeys(int index) {
      return keys_.get(index);
    }
    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>repeated string keys = 2;</code>
     */
    public com.google.protobuf.ByteString
        getKeysBytes(int index) {
      return keys_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (trace_ != null) {
        output.writeMessage(1, getTrace());
      }
      for (int i = 0; i < keys_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, keys_.getRaw(i));
      }
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, key_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (trace_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTrace());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < keys_.size(); i++) {
          dataSize += computeStringSizeNoTag(keys_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getKeysList().size();
      }
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, key_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof KFCRequest)) {
        return super.equals(obj);
      }
      KFCRequest other = (KFCRequest) obj;

      boolean result = true;
      result = result && (hasTrace() == other.hasTrace());
      if (hasTrace()) {
        result = result && getTrace()
            .equals(other.getTrace());
      }
      result = result && getKey()
          .equals(other.getKey());
      result = result && getKeysList()
          .equals(other.getKeysList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTrace()) {
        hash = (37 * hash) + TRACE_FIELD_NUMBER;
        hash = (53 * hash) + getTrace().hashCode();
      }
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      if (getKeysCount() > 0) {
        hash = (37 * hash) + KEYS_FIELD_NUMBER;
        hash = (53 * hash) + getKeysList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static KFCRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KFCRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KFCRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KFCRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KFCRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KFCRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KFCRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static KFCRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static KFCRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static KFCRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static KFCRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static KFCRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(KFCRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * use db:key
     * example: mid_blacklist:3479095
     * </pre>
     *
     * Protobuf type {@code ai.kfc.KFCRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ai.kfc.KFCRequest)
        KFCRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return KfcMessage.internal_static_ai_kfc_KFCRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return KfcMessage.internal_static_ai_kfc_KFCRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                KFCRequest.class, Builder.class);
      }

      // Construct using ai.kfc.KfcMessage.KFCRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (traceBuilder_ == null) {
          trace_ = null;
        } else {
          trace_ = null;
          traceBuilder_ = null;
        }
        key_ = "";

        keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return KfcMessage.internal_static_ai_kfc_KFCRequest_descriptor;
      }

      public KFCRequest getDefaultInstanceForType() {
        return KFCRequest.getDefaultInstance();
      }

      public KFCRequest build() {
        KFCRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public KFCRequest buildPartial() {
        KFCRequest result = new KFCRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (traceBuilder_ == null) {
          result.trace_ = trace_;
        } else {
          result.trace_ = traceBuilder_.build();
        }
        result.key_ = key_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          keys_ = keys_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.keys_ = keys_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof KFCRequest) {
          return mergeFrom((KFCRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(KFCRequest other) {
        if (other == KFCRequest.getDefaultInstance()) return this;
        if (other.hasTrace()) {
          mergeTrace(other.getTrace());
        }
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (!other.keys_.isEmpty()) {
          if (keys_.isEmpty()) {
            keys_ = other.keys_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureKeysIsMutable();
            keys_.addAll(other.keys_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        KFCRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (KFCRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private ai.Trace.TraceArg trace_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ai.Trace.TraceArg, ai.Trace.TraceArg.Builder, ai.Trace.TraceArgOrBuilder> traceBuilder_;
      /**
       * <code>.ai.TraceArg trace = 1;</code>
       */
      public boolean hasTrace() {
        return traceBuilder_ != null || trace_ != null;
      }
      /**
       * <code>.ai.TraceArg trace = 1;</code>
       */
      public ai.Trace.TraceArg getTrace() {
        if (traceBuilder_ == null) {
          return trace_ == null ? ai.Trace.TraceArg.getDefaultInstance() : trace_;
        } else {
          return traceBuilder_.getMessage();
        }
      }
      /**
       * <code>.ai.TraceArg trace = 1;</code>
       */
      public Builder setTrace(ai.Trace.TraceArg value) {
        if (traceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          trace_ = value;
          onChanged();
        } else {
          traceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ai.TraceArg trace = 1;</code>
       */
      public Builder setTrace(
          ai.Trace.TraceArg.Builder builderForValue) {
        if (traceBuilder_ == null) {
          trace_ = builderForValue.build();
          onChanged();
        } else {
          traceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ai.TraceArg trace = 1;</code>
       */
      public Builder mergeTrace(ai.Trace.TraceArg value) {
        if (traceBuilder_ == null) {
          if (trace_ != null) {
            trace_ =
              ai.Trace.TraceArg.newBuilder(trace_).mergeFrom(value).buildPartial();
          } else {
            trace_ = value;
          }
          onChanged();
        } else {
          traceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ai.TraceArg trace = 1;</code>
       */
      public Builder clearTrace() {
        if (traceBuilder_ == null) {
          trace_ = null;
          onChanged();
        } else {
          trace_ = null;
          traceBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ai.TraceArg trace = 1;</code>
       */
      public ai.Trace.TraceArg.Builder getTraceBuilder() {
        
        onChanged();
        return getTraceFieldBuilder().getBuilder();
      }
      /**
       * <code>.ai.TraceArg trace = 1;</code>
       */
      public ai.Trace.TraceArgOrBuilder getTraceOrBuilder() {
        if (traceBuilder_ != null) {
          return traceBuilder_.getMessageOrBuilder();
        } else {
          return trace_ == null ?
              ai.Trace.TraceArg.getDefaultInstance() : trace_;
        }
      }
      /**
       * <code>.ai.TraceArg trace = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ai.Trace.TraceArg, ai.Trace.TraceArg.Builder, ai.Trace.TraceArgOrBuilder> 
          getTraceFieldBuilder() {
        if (traceBuilder_ == null) {
          traceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ai.Trace.TraceArg, ai.Trace.TraceArg.Builder, ai.Trace.TraceArgOrBuilder>(
                  getTrace(),
                  getParentForChildren(),
                  isClean());
          trace_ = null;
        }
        return traceBuilder_;
      }

      private Object key_ = "";
      /**
       * <code>string key = 3;</code>
       */
      public String getKey() {
        Object ref = key_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string key = 3;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 3;</code>
       */
      public Builder setKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 3;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 3;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureKeysIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          keys_ = new com.google.protobuf.LazyStringArrayList(keys_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       * deprecated
       * </pre>
       *
       * <code>repeated string keys = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getKeysList() {
        return keys_.getUnmodifiableView();
      }
      /**
       * <pre>
       * deprecated
       * </pre>
       *
       * <code>repeated string keys = 2;</code>
       */
      public int getKeysCount() {
        return keys_.size();
      }
      /**
       * <pre>
       * deprecated
       * </pre>
       *
       * <code>repeated string keys = 2;</code>
       */
      public String getKeys(int index) {
        return keys_.get(index);
      }
      /**
       * <pre>
       * deprecated
       * </pre>
       *
       * <code>repeated string keys = 2;</code>
       */
      public com.google.protobuf.ByteString
          getKeysBytes(int index) {
        return keys_.getByteString(index);
      }
      /**
       * <pre>
       * deprecated
       * </pre>
       *
       * <code>repeated string keys = 2;</code>
       */
      public Builder setKeys(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeysIsMutable();
        keys_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * deprecated
       * </pre>
       *
       * <code>repeated string keys = 2;</code>
       */
      public Builder addKeys(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeysIsMutable();
        keys_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * deprecated
       * </pre>
       *
       * <code>repeated string keys = 2;</code>
       */
      public Builder addAllKeys(
          Iterable<String> values) {
        ensureKeysIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, keys_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * deprecated
       * </pre>
       *
       * <code>repeated string keys = 2;</code>
       */
      public Builder clearKeys() {
        keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * deprecated
       * </pre>
       *
       * <code>repeated string keys = 2;</code>
       */
      public Builder addKeysBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureKeysIsMutable();
        keys_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ai.kfc.KFCRequest)
    }

    // @@protoc_insertion_point(class_scope:ai.kfc.KFCRequest)
    private static final KFCRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new KFCRequest();
    }

    public static KFCRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KFCRequest>
        PARSER = new com.google.protobuf.AbstractParser<KFCRequest>() {
      public KFCRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KFCRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KFCRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<KFCRequest> getParserForType() {
      return PARSER;
    }

    public KFCRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface KFCResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ai.kfc.KFCResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string debug = 1;</code>
     */
    String getDebug();
    /**
     * <code>string debug = 1;</code>
     */
    com.google.protobuf.ByteString
        getDebugBytes();

    /**
     * <code>bytes value = 3;</code>
     */
    com.google.protobuf.ByteString getValue();

    /**
     * <code>map&lt;string, .ai.kfc.KFCResponse.Result&gt; results = 2;</code>
     */
    int getResultsCount();
    /**
     * <code>map&lt;string, .ai.kfc.KFCResponse.Result&gt; results = 2;</code>
     */
    boolean containsResults(
        String key);
    /**
     * Use {@link #getResultsMap()} instead.
     */
    @Deprecated
    java.util.Map<String, KFCResponse.Result>
    getResults();
    /**
     * <code>map&lt;string, .ai.kfc.KFCResponse.Result&gt; results = 2;</code>
     */
    java.util.Map<String, KFCResponse.Result>
    getResultsMap();
    /**
     * <code>map&lt;string, .ai.kfc.KFCResponse.Result&gt; results = 2;</code>
     */

    KFCResponse.Result getResultsOrDefault(
        String key,
        KFCResponse.Result defaultValue);
    /**
     * <code>map&lt;string, .ai.kfc.KFCResponse.Result&gt; results = 2;</code>
     */

    KFCResponse.Result getResultsOrThrow(
        String key);
  }
  /**
   * Protobuf type {@code ai.kfc.KFCResponse}
   */
  public  static final class KFCResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ai.kfc.KFCResponse)
      KFCResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KFCResponse.newBuilder() to construct.
    private KFCResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KFCResponse() {
      debug_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KFCResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              debug_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                results_ = com.google.protobuf.MapField.newMapField(
                    ResultsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<String, Result>
              results__ = input.readMessage(
                  ResultsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              results_.getMutableMap().put(
                  results__.getKey(), results__.getValue());
              break;
            }
            case 26: {

              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return KfcMessage.internal_static_ai_kfc_KFCResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetResults();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return KfcMessage.internal_static_ai_kfc_KFCResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              KFCResponse.class, Builder.class);
    }

    public interface ResultOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ai.kfc.KFCResponse.Result)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>bytes value = 1;</code>
       */
      com.google.protobuf.ByteString getValue();

      /**
       * <code>string error = 2;</code>
       */
      String getError();
      /**
       * <code>string error = 2;</code>
       */
      com.google.protobuf.ByteString
          getErrorBytes();

      public Result.ResultCase getResultCase();
    }
    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * Protobuf type {@code ai.kfc.KFCResponse.Result}
     */
    public  static final class Result extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:ai.kfc.KFCResponse.Result)
        ResultOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Result.newBuilder() to construct.
      private Result(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Result() {
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Result(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                resultCase_ = 1;
                result_ = input.readBytes();
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();
                resultCase_ = 2;
                result_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return KfcMessage.internal_static_ai_kfc_KFCResponse_Result_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return KfcMessage.internal_static_ai_kfc_KFCResponse_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Result.class, Builder.class);
      }

      private int resultCase_ = 0;
      private Object result_;
      public enum ResultCase
          implements com.google.protobuf.Internal.EnumLite {
        VALUE(1),
        ERROR(2),
        RESULT_NOT_SET(0);
        private final int value;
        private ResultCase(int value) {
          this.value = value;
        }
        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static ResultCase valueOf(int value) {
          return forNumber(value);
        }

        public static ResultCase forNumber(int value) {
          switch (value) {
            case 1: return VALUE;
            case 2: return ERROR;
            case 0: return RESULT_NOT_SET;
            default: return null;
          }
        }
        public int getNumber() {
          return this.value;
        }
      };

      public ResultCase
      getResultCase() {
        return ResultCase.forNumber(
            resultCase_);
      }

      public static final int VALUE_FIELD_NUMBER = 1;
      /**
       * <code>bytes value = 1;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        if (resultCase_ == 1) {
          return (com.google.protobuf.ByteString) result_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }

      public static final int ERROR_FIELD_NUMBER = 2;
      /**
       * <code>string error = 2;</code>
       */
      public String getError() {
        Object ref = "";
        if (resultCase_ == 2) {
          ref = result_;
        }
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (resultCase_ == 2) {
            result_ = s;
          }
          return s;
        }
      }
      /**
       * <code>string error = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        Object ref = "";
        if (resultCase_ == 2) {
          ref = result_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          if (resultCase_ == 2) {
            result_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (resultCase_ == 1) {
          output.writeBytes(
              1, (com.google.protobuf.ByteString) result_);
        }
        if (resultCase_ == 2) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, result_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (resultCase_ == 1) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(
                1, (com.google.protobuf.ByteString) result_);
        }
        if (resultCase_ == 2) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, result_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Result)) {
          return super.equals(obj);
        }
        Result other = (Result) obj;

        boolean result = true;
        result = result && getResultCase().equals(
            other.getResultCase());
        if (!result) return false;
        switch (resultCase_) {
          case 1:
            result = result && getValue()
                .equals(other.getValue());
            break;
          case 2:
            result = result && getError()
                .equals(other.getError());
            break;
          case 0:
          default:
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        switch (resultCase_) {
          case 1:
            hash = (37 * hash) + VALUE_FIELD_NUMBER;
            hash = (53 * hash) + getValue().hashCode();
            break;
          case 2:
            hash = (37 * hash) + ERROR_FIELD_NUMBER;
            hash = (53 * hash) + getError().hashCode();
            break;
          case 0:
          default:
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Result parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Result parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Result parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Result parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Result parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Result parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Result parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Result parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Result parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Result parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Result parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Result parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Result prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * deprecated
       * </pre>
       *
       * Protobuf type {@code ai.kfc.KFCResponse.Result}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ai.kfc.KFCResponse.Result)
          ResultOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return KfcMessage.internal_static_ai_kfc_KFCResponse_Result_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return KfcMessage.internal_static_ai_kfc_KFCResponse_Result_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Result.class, Builder.class);
        }

        // Construct using ai.kfc.KfcMessage.KFCResponse.Result.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          resultCase_ = 0;
          result_ = null;
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return KfcMessage.internal_static_ai_kfc_KFCResponse_Result_descriptor;
        }

        public Result getDefaultInstanceForType() {
          return Result.getDefaultInstance();
        }

        public Result build() {
          Result result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Result buildPartial() {
          Result result = new Result(this);
          if (resultCase_ == 1) {
            result.result_ = result_;
          }
          if (resultCase_ == 2) {
            result.result_ = result_;
          }
          result.resultCase_ = resultCase_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Result) {
            return mergeFrom((Result)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Result other) {
          if (other == Result.getDefaultInstance()) return this;
          switch (other.getResultCase()) {
            case VALUE: {
              setValue(other.getValue());
              break;
            }
            case ERROR: {
              resultCase_ = 2;
              result_ = other.result_;
              onChanged();
              break;
            }
            case RESULT_NOT_SET: {
              break;
            }
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Result parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Result) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int resultCase_ = 0;
        private Object result_;
        public ResultCase
            getResultCase() {
          return ResultCase.forNumber(
              resultCase_);
        }

        public Builder clearResult() {
          resultCase_ = 0;
          result_ = null;
          onChanged();
          return this;
        }


        /**
         * <code>bytes value = 1;</code>
         */
        public com.google.protobuf.ByteString getValue() {
          if (resultCase_ == 1) {
            return (com.google.protobuf.ByteString) result_;
          }
          return com.google.protobuf.ByteString.EMPTY;
        }
        /**
         * <code>bytes value = 1;</code>
         */
        public Builder setValue(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  resultCase_ = 1;
          result_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bytes value = 1;</code>
         */
        public Builder clearValue() {
          if (resultCase_ == 1) {
            resultCase_ = 0;
            result_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <code>string error = 2;</code>
         */
        public String getError() {
          Object ref = "";
          if (resultCase_ == 2) {
            ref = result_;
          }
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (resultCase_ == 2) {
              result_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string error = 2;</code>
         */
        public com.google.protobuf.ByteString
            getErrorBytes() {
          Object ref = "";
          if (resultCase_ == 2) {
            ref = result_;
          }
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            if (resultCase_ == 2) {
              result_ = b;
            }
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string error = 2;</code>
         */
        public Builder setError(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  resultCase_ = 2;
          result_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string error = 2;</code>
         */
        public Builder clearError() {
          if (resultCase_ == 2) {
            resultCase_ = 0;
            result_ = null;
            onChanged();
          }
          return this;
        }
        /**
         * <code>string error = 2;</code>
         */
        public Builder setErrorBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          resultCase_ = 2;
          result_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:ai.kfc.KFCResponse.Result)
      }

      // @@protoc_insertion_point(class_scope:ai.kfc.KFCResponse.Result)
      private static final Result DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Result();
      }

      public static Result getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Result>
          PARSER = new com.google.protobuf.AbstractParser<Result>() {
        public Result parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Result(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Result> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<Result> getParserForType() {
        return PARSER;
      }

      public Result getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int DEBUG_FIELD_NUMBER = 1;
    private volatile Object debug_;
    /**
     * <code>string debug = 1;</code>
     */
    public String getDebug() {
      Object ref = debug_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        debug_ = s;
        return s;
      }
    }
    /**
     * <code>string debug = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDebugBytes() {
      Object ref = debug_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        debug_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>bytes value = 3;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    public static final int RESULTS_FIELD_NUMBER = 2;
    private static final class ResultsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, Result> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, Result>newDefaultInstance(
                  KfcMessage.internal_static_ai_kfc_KFCResponse_ResultsEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  Result.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        String, Result> results_;
    private com.google.protobuf.MapField<String, Result>
    internalGetResults() {
      if (results_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ResultsDefaultEntryHolder.defaultEntry);
      }
      return results_;
    }

    public int getResultsCount() {
      return internalGetResults().getMap().size();
    }
    /**
     * <code>map&lt;string, .ai.kfc.KFCResponse.Result&gt; results = 2;</code>
     */

    public boolean containsResults(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetResults().getMap().containsKey(key);
    }
    /**
     * Use {@link #getResultsMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, Result> getResults() {
      return getResultsMap();
    }
    /**
     * <code>map&lt;string, .ai.kfc.KFCResponse.Result&gt; results = 2;</code>
     */

    public java.util.Map<String, Result> getResultsMap() {
      return internalGetResults().getMap();
    }
    /**
     * <code>map&lt;string, .ai.kfc.KFCResponse.Result&gt; results = 2;</code>
     */

    public Result getResultsOrDefault(
        String key,
        Result defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, Result> map =
          internalGetResults().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .ai.kfc.KFCResponse.Result&gt; results = 2;</code>
     */

    public Result getResultsOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, Result> map =
          internalGetResults().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDebugBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, debug_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetResults(),
          ResultsDefaultEntryHolder.defaultEntry,
          2);
      if (!value_.isEmpty()) {
        output.writeBytes(3, value_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDebugBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, debug_);
      }
      for (java.util.Map.Entry<String, Result> entry
           : internalGetResults().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, Result>
        results__ = ResultsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, results__);
      }
      if (!value_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof KFCResponse)) {
        return super.equals(obj);
      }
      KFCResponse other = (KFCResponse) obj;

      boolean result = true;
      result = result && getDebug()
          .equals(other.getDebug());
      result = result && getValue()
          .equals(other.getValue());
      result = result && internalGetResults().equals(
          other.internalGetResults());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEBUG_FIELD_NUMBER;
      hash = (53 * hash) + getDebug().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      if (!internalGetResults().getMap().isEmpty()) {
        hash = (37 * hash) + RESULTS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetResults().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static KFCResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KFCResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KFCResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KFCResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KFCResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KFCResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KFCResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static KFCResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static KFCResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static KFCResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static KFCResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static KFCResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(KFCResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ai.kfc.KFCResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ai.kfc.KFCResponse)
        KFCResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return KfcMessage.internal_static_ai_kfc_KFCResponse_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetResults();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableResults();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return KfcMessage.internal_static_ai_kfc_KFCResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                KFCResponse.class, Builder.class);
      }

      // Construct using ai.kfc.KfcMessage.KFCResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        debug_ = "";

        value_ = com.google.protobuf.ByteString.EMPTY;

        internalGetMutableResults().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return KfcMessage.internal_static_ai_kfc_KFCResponse_descriptor;
      }

      public KFCResponse getDefaultInstanceForType() {
        return KFCResponse.getDefaultInstance();
      }

      public KFCResponse build() {
        KFCResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public KFCResponse buildPartial() {
        KFCResponse result = new KFCResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.debug_ = debug_;
        result.value_ = value_;
        result.results_ = internalGetResults();
        result.results_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof KFCResponse) {
          return mergeFrom((KFCResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(KFCResponse other) {
        if (other == KFCResponse.getDefaultInstance()) return this;
        if (!other.getDebug().isEmpty()) {
          debug_ = other.debug_;
          onChanged();
        }
        if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
          setValue(other.getValue());
        }
        internalGetMutableResults().mergeFrom(
            other.internalGetResults());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        KFCResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (KFCResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object debug_ = "";
      /**
       * <code>string debug = 1;</code>
       */
      public String getDebug() {
        Object ref = debug_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          debug_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string debug = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDebugBytes() {
        Object ref = debug_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          debug_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string debug = 1;</code>
       */
      public Builder setDebug(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        debug_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string debug = 1;</code>
       */
      public Builder clearDebug() {
        
        debug_ = getDefaultInstance().getDebug();
        onChanged();
        return this;
      }
      /**
       * <code>string debug = 1;</code>
       */
      public Builder setDebugBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        debug_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes value = 3;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>bytes value = 3;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes value = 3;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, Result> results_;
      private com.google.protobuf.MapField<String, Result>
      internalGetResults() {
        if (results_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ResultsDefaultEntryHolder.defaultEntry);
        }
        return results_;
      }
      private com.google.protobuf.MapField<String, Result>
      internalGetMutableResults() {
        onChanged();;
        if (results_ == null) {
          results_ = com.google.protobuf.MapField.newMapField(
              ResultsDefaultEntryHolder.defaultEntry);
        }
        if (!results_.isMutable()) {
          results_ = results_.copy();
        }
        return results_;
      }

      public int getResultsCount() {
        return internalGetResults().getMap().size();
      }
      /**
       * <code>map&lt;string, .ai.kfc.KFCResponse.Result&gt; results = 2;</code>
       */

      public boolean containsResults(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetResults().getMap().containsKey(key);
      }
      /**
       * Use {@link #getResultsMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, Result> getResults() {
        return getResultsMap();
      }
      /**
       * <code>map&lt;string, .ai.kfc.KFCResponse.Result&gt; results = 2;</code>
       */

      public java.util.Map<String, Result> getResultsMap() {
        return internalGetResults().getMap();
      }
      /**
       * <code>map&lt;string, .ai.kfc.KFCResponse.Result&gt; results = 2;</code>
       */

      public Result getResultsOrDefault(
          String key,
          Result defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, Result> map =
            internalGetResults().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .ai.kfc.KFCResponse.Result&gt; results = 2;</code>
       */

      public Result getResultsOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, Result> map =
            internalGetResults().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearResults() {
        internalGetMutableResults().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .ai.kfc.KFCResponse.Result&gt; results = 2;</code>
       */

      public Builder removeResults(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableResults().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, Result>
      getMutableResults() {
        return internalGetMutableResults().getMutableMap();
      }
      /**
       * <code>map&lt;string, .ai.kfc.KFCResponse.Result&gt; results = 2;</code>
       */
      public Builder putResults(
          String key,
          Result value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableResults().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .ai.kfc.KFCResponse.Result&gt; results = 2;</code>
       */

      public Builder putAllResults(
          java.util.Map<String, Result> values) {
        internalGetMutableResults().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ai.kfc.KFCResponse)
    }

    // @@protoc_insertion_point(class_scope:ai.kfc.KFCResponse)
    private static final KFCResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new KFCResponse();
    }

    public static KFCResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KFCResponse>
        PARSER = new com.google.protobuf.AbstractParser<KFCResponse>() {
      public KFCResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KFCResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KFCResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<KFCResponse> getParserForType() {
      return PARSER;
    }

    public KFCResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_kfc_KFCRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ai_kfc_KFCRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_kfc_KFCResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ai_kfc_KFCResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_kfc_KFCResponse_Result_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ai_kfc_KFCResponse_Result_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_kfc_KFCResponse_ResultsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ai_kfc_KFCResponse_ResultsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021kfc_message.proto\022\006ai.kfc\032\020misc/trace." +
      "proto\"D\n\nKFCRequest\022\033\n\005trace\030\001 \001(\0132\014.ai." +
      "TraceArg\022\013\n\003key\030\003 \001(\t\022\014\n\004keys\030\002 \003(\t\"\340\001\n\013" +
      "KFCResponse\022\r\n\005debug\030\001 \001(\t\022\r\n\005value\030\003 \001(" +
      "\014\0221\n\007results\030\002 \003(\0132 .ai.kfc.KFCResponse." +
      "ResultsEntry\0324\n\006Result\022\017\n\005value\030\001 \001(\014H\000\022" +
      "\017\n\005error\030\002 \001(\tH\000B\010\n\006result\032J\n\014ResultsEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022)\n\005value\030\002 \001(\0132\032.ai.kfc." +
      "KFCResponse.Result:\0028\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ai.Trace.getDescriptor(),
        }, assigner);
    internal_static_ai_kfc_KFCRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ai_kfc_KFCRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ai_kfc_KFCRequest_descriptor,
        new String[] { "Trace", "Key", "Keys", });
    internal_static_ai_kfc_KFCResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ai_kfc_KFCResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ai_kfc_KFCResponse_descriptor,
        new String[] { "Debug", "Value", "Results", });
    internal_static_ai_kfc_KFCResponse_Result_descriptor =
      internal_static_ai_kfc_KFCResponse_descriptor.getNestedTypes().get(0);
    internal_static_ai_kfc_KFCResponse_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ai_kfc_KFCResponse_Result_descriptor,
        new String[] { "Value", "Error", "Result", });
    internal_static_ai_kfc_KFCResponse_ResultsEntry_descriptor =
      internal_static_ai_kfc_KFCResponse_descriptor.getNestedTypes().get(1);
    internal_static_ai_kfc_KFCResponse_ResultsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ai_kfc_KFCResponse_ResultsEntry_descriptor,
        new String[] { "Key", "Value", });
    ai.Trace.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
